Algoritmo "ValorDoRetangulo"
//
//
// Disciplina  : [Lógica de programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Escreva um algoritimo para ler as dimensões de um retângulo (base e altura), calcular e estcrever a área do retângulo
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/08/2026
Var
// Seção de Declarações das variáveis
 base: real
 altura: real
 area: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreval ("Área do retângulo")
Escreval ("Digite o valor da base:")
Leia (base)
Escreval ("Digite o valor da altura")
Leia (altura)
area<- base*altura
Escreval ("A Área do retângulo é:", area)

Fimalgoritmo