Algoritmo "Antecessor"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Exemplo estrutura de decisão simples
// Autor(a)    : Gabriel Vitor
// Data atual  : 21/09/2026

Var
   numero, antecessor: Inteiro
Inicio
   Escreva("Digite um número inteiro: ")
   Leia(numero)

   antecessor <- numero - 1

   Escreva("O antecessor de ", numero, " é: ", antecessor)
fimalgoritmo